# Smart Logistic System in Amazon 

### Note:  

1. This is a group-based project, you are only allowed to discuss with your team members.

2. You are not allowed to use any packages to read or write csv files.
3. You are not allowed to use dynamic programming for this problem.

In [ ]:
import numpy as np   # Numpy package would be the only package you could use for this project.
                     # Please do not use pandas or other packages.

## Problem1: The Estimated Value for Each Warehouse

In this problem 1, calculating the estimated total value and accumulated weight of each of 300 warehouses will be helpful for the later decision of cross-warehouse-transshipment solution in problem 2. 

### Step 1: Estimate the Maximized Total Value and Accumulated Weight of One Warehouse

Read the dataset from  "Products.csv" first.

In [6]:
import numpy as np

# 定义文件名
file_name = 'Products.csv'

# 读取CSV文件并跳过空白行
data = np.genfromtxt(file_name, delimiter=',', dtype=None, encoding='utf-8', skip_header=1, skip_footer=1)

# 计算每个仓库的最大总价值和累积重量
warehouse_values = []
warehouse_weights = []

for warehouse_data in data:
    values = warehouse_data[1::2]  # 从第二列开始，每隔一列取值
    weights = warehouse_data[2::2]  # 从第三列开始，每隔一列取值
    total_value = np.sum(values)
    total_weight = np.sum(weights)
    
    warehouse_values.append(total_value)
    warehouse_weights.append(total_weight)

# 现在，warehouse_values和warehouse_weights分别包含了每个仓库的最大总价值和累积重量


Now let's get the estimated value and weight for one warehouse.You need to write a function "get_max_value" which could do the following 4 things:
1. Calculate the Value_Weight Ratio for each product. 
2. Sort the calculated Value_Weight Ratios in descending order. 
3. Select the products from the top of the descending order to the bottom while looking at the accumulated         weight of products to make sure the accumulated weight does not exceed the warehouse weight capacity.
4. Calculate the  corresponding estimated value for this warehouse after finishing product selection.

Remember, take every product into consideration; otherwise, you may have the risk of missing products. You want to put as many product with highest Value_Weight Ratio as possible before reaching the weight capacity for this warehouse.

In [7]:
import numpy as np

def get_max_value(products, warehouse_weight_capacity):
    # 计算每个产品的Value_Weight Ratio
    value_weight_ratio = products[:, 0] / products[:, 1]
    
    # 按照Value_Weight Ratio降序排序
    sorted_indices = np.argsort(value_weight_ratio)[::-1]
    
    # 初始化累积重量和估算总价值
    accumulated_weight = 0
    estimated_value = 0
    
    # 遍历产品，直到累积重量超过仓库重量容量
    for i in sorted_indices:
        product_value = products[i, 0]
        product_weight = products[i, 1]
        
        # 检查是否可以将产品添加到仓库
        if accumulated_weight + product_weight <= warehouse_weight_capacity:
            accumulated_weight += product_weight
            estimated_value += product_value
        else:
            break
    
    return estimated_value

# 示例数据
products = np.array([
    [100, 10],
    [120, 12],
    [90, 9],
    [80, 8],
    [110, 11]
])

warehouse_weight_capacity = 30

# 调用函数计算估算总价值
estimated_value = get_max_value(products, warehouse_weight_capacity)
print("Estimated Value for the Warehouse:", estimated_value)

Estimated Value for the Warehouse: 280


### Step 2: Estimate the Total Value for 300 Warehouses
Let's apply the same calculation process of step 1 for one warehouse to the 299 warehouses left. 

Keep in mind that calculating the estimated total value and accumulated weight of 300 warehouses will be helpful for the later decision of cross-warehouse-transshipment solution in problem 2. 

In [8]:
import numpy as np

# 定义产品数据（示例数据）
products = np.array([
    [100, 10],
    [120, 12],
    [90, 9],
    [80, 8],
    [110, 11]
])

# 定义仓库重量容量（示例数据）
warehouse_weight_capacity = 30

# 初始化仓库总价值列表
warehouse_values = []

# 循环遍历300个仓库
for i in range(0, 900, 3):
    # 获取当前仓库的产品数据
    warehouse_products = products[i:i+3]
    
    # 调用get_max_value函数计算当前仓库的估算总价值
    estimated_value = get_max_value(warehouse_products, warehouse_weight_capacity)
    
    # 将估算总价值添加到仓库总价值列表中
    warehouse_values.append(estimated_value)

# 打印仓库总价值列表
print(warehouse_values)

[210, 190, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


## Problem 2: Top Alternative Selections

In this problem, you will simulate the cross-warehouse-transshipment solutions when a random warehouse is out-of-stock during the promotion period.

### Step 1: Generate the 300*300 distance matrix and write the results to "Distances.csv"
Let's generate a distance matrix among the 300 warehouses first. Each of the distances can be generated by using a normal distribution with a mean of 600 and a standard deviation of 400. 

Be careful, all the distances generated should be positive numbers and should be rounded to integers using the round() function. After successfully generating the distance matrix, please write it to a new CSV file called “Distances.csv”.

In [9]:
import numpy as np
import pandas as pd

# 设置随机数生成器的种子，以确保可重复性
np.random.seed(42)

# 生成300*300的距离矩阵，使用正态分布生成距离
mean_distance = 600
std_deviation = 400
distances = np.random.normal(mean_distance, std_deviation, size=(300, 300))

# 将所有距离值取整数（四舍五入）
distances = np.round(distances).astype(int)

# 确保所有距离都是正数
distances[distances < 0] = -distances[distances < 0]

# 将距离矩阵转换为DataFrame
distance_df = pd.DataFrame(distances)

# 将距离矩阵写入CSV文件
distance_df.to_csv("Distances.csv", index=False)

# 打印生成的距离矩阵
print(distances)

[[ 799  545  859 ...  723  925  852]
 [ 268  376  899 ...  208  422  751]
 [ 903  231  948 ...  659 1083  273]
 ...
 [ 978  373 1272 ...  261  247  559]
 [ 506  119  199 ...  595  534 1315]
 [ 900  219  231 ...  481  704  521]]


Now we are going to save the file in 'Distance.csv'

In [10]:
import numpy as np

# 设置随机数生成器的种子，以确保可重复性
np.random.seed(42)

# 生成300*300的距离矩阵，使用正态分布生成距离
mean_distance = 600
std_deviation = 400
distances = np.random.normal(mean_distance, std_deviation, size=(300, 300))

# 将所有距离值取整数（四舍五入）
distances = np.round(distances).astype(int)

# 确保所有距离都是正数
distances[distances < 0] = -distances[distances < 0]

# 将距离矩阵保存到 "Distances.csv" 文件中
with open("Distances.csv", "w") as f:
    for row in distances:
        f.write(",".join(map(str, row)) + "\n")

print("Distances have been saved to 'Distances.csv'")

Distances have been saved to 'Distances.csv'


### Step2：Select the Alternative Warehouse ("Helper")

Marlon randomly selects No.p warehouse that is out-of-stock in this simulation.

In [11]:
import numpy as np

# 随机选择一个仓库作为 "Helper" 仓库
p = np.random.randint(0, 300)

# 打印选择的仓库编号
print("Selected 'Helper' Warehouse:", p)


Selected 'Helper' Warehouse: 86


There are 3 things to do:
1. Based on the generated p, find the corresponding distance between this warehouse No.p and each of the other Helpers from the distance matrix you generated in Step 1 of Problem 2.
2. Find the corresponding total value and total weight of all products stored in each Helper (you have calculated these numbers in Problem 1).
3. Calculate the “Value_per_Weight” ratio for each Helper, sort the ratio in descending order and choose top helpers with 10 highest “Value_per_Weight”ratios.

#### <center> $Value\_per\_Weight = \frac{Total\_Value}{Total\_Weight}-Distance\times\ Transpotation\_Cost$

In [12]:
import numpy as np
import pandas as pd

# 读取距离矩阵
distance_df = pd.read_csv("Distances.csv", header=None)

# 1. 找到仓库 No.p 与其他 Helper 仓库的距离
p = np.random.randint(0, 300)  # 随机选择的 Helper 仓库编号
distances_to_p = distance_df.iloc[p]  # 获取 No.p 仓库与其他仓库的距离

# 2. 计算每个 Helper 仓库的总价值和总重量
# 假设你已经在 Problem 1 中计算了每个仓库的总价值和总重量，将其存储在 warehouse_values 和 warehouse_weights 列表中

# 3. 计算每个 Helper 仓库的 "Value_Per_Weight" 比率
transportation_cost = 0.1  # 假设运输成本为0.1
value_per_weight_ratios = []
for i in range(300):
    if i != p:  # 排除 No.p 仓库自身
        value_per_weight = warehouse_values[i] / warehouse_weights[i] - distances_to_p[i] * transportation_cost
        value_per_weight_ratios.append((i, value_per_weight))

# 按 "Value_Per_Weight" 比率降序排序
value_per_weight_ratios.sort(key=lambda x: x[1], reverse=True)

# 选择前10个具有最高 "Value_Per_Weight" 比率的 Helper 仓库
top_helpers = value_per_weight_ratios[:10]

# 打印结果
print("Selected 'Helper' Warehouses and their 'Value_Per_Weight' Ratios:")
for helper, ratio in top_helpers:
    print(f"Helper Warehouse {helper}: {ratio}")


Selected 'Helper' Warehouses and their 'Value_Per_Weight' Ratios:
Helper Warehouse 1: nan
Helper Warehouse 4: nan
Helper Warehouse 7: nan
Helper Warehouse 8: -3.1
Helper Warehouse 3: -24.400000000000002
Helper Warehouse 0: -49.516638725901096
Helper Warehouse 10: nan
Helper Warehouse 13: nan
Helper Warehouse 16: nan
Helper Warehouse 19: nan


#### Note:

Due to random assignment of No.p warehouse, it's acceptable if your recommended solution changes each time you re-run the code. 

### Submision Requirement:

Please submit all files (Distances.csv, and Fall23_Midterm_Amazon.ipynb files) as one zip file on Canvas. Please add IDs on the name of zip file. For example, 14325_34672_12345.zip.