In [1]:
List1=[1,2,3,4,5]
List2=[6,7,8,9,10]
List1+List2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
import numpy as np
Array1=np.array(List1)
Array2=np.array(List2)
Array1+Array2

array([ 7,  9, 11, 13, 15])

In [5]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
b=a.T
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [4]:
np.random.randint(1,5)

3

In [5]:
np.random.randint(1,5,4)

array([4, 4, 3, 1])

In [6]:
np.random.normal(5,3)

1.8773261262429148

In [7]:
np.random.normal(5,3,4)

array([0.191148  , 5.19189961, 7.61805035, 1.05180147])

In [8]:
np.random.normal(5,3,(2,2))

array([[5.83509149, 3.3816269 ],
       [8.18117717, 2.96212223]])

In [11]:
c=np.array([[0,992,855,423,803],[0,0,276,538,553],[0,0,0,217,561],[0,0,0,0,262],[0,0,0,0,0]])
c

array([[  0, 992, 855, 423, 803],
       [  0,   0, 276, 538, 553],
       [  0,   0,   0, 217, 561],
       [  0,   0,   0,   0, 262],
       [  0,   0,   0,   0,   0]])

In [13]:
d=c.T
d

array([[  0,   0,   0,   0,   0],
       [992,   0,   0,   0,   0],
       [855, 276,   0,   0,   0],
       [423, 538, 217,   0,   0],
       [803, 553, 561, 262,   0]])

In [14]:
c+d

array([[  0, 992, 855, 423, 803],
       [992,   0, 276, 538, 553],
       [855, 276,   0, 217, 561],
       [423, 538, 217,   0, 262],
       [803, 553, 561, 262,   0]])